### ISSUE TITLE
Issue in formAPI example

### ISSUE THREAD

**Issue by addamove** [zerobias/effector#249] opened 2019-11-18 20:36 UTC
Form example from readme gives me 

`TypeError: Cannot read property 'h3' of undefined
    at ne (effector.master.js:1:9906)
    at re (effector.master.js:1:10259)
    at Function.b.create (effector.master.js:1:1248)
    at Object.b [as upsertField] (effector.master.js:1:1198)`

https://share.effector.dev/ZvWx6ZBn

**Comment by zerobias** [comment] 2019-11-18 22:42
Cannot reproduce it, which browser are you use?
Also make sure that the localStorage contains the correct data (or no data at all)

**Comment by zerobias** [comment] 2019-11-21 13:13
Looks like it was fixed in [this](https://github.com/zerobias/effector/commit/d06fd7a50f5af8eeb490b354cff4a26de5bf9df6) commit.

The issue was in usage of repl's _own_ `effector-react` inside of executed code, which leads to using different `effector`'s versions at the same time. That commit allowed us to use independent version of `effector-react`

Feel free to open new issue if you notice something wrong again

**Closed by zerobias** 2019-11-21 13:13 UTC
Labels: bug, needs triage
